# Generated by Django 3.0 on 2021-04-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_cover_image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
