# Generated by Django 3.0 on 2021-04-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_blog_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_cover_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
